export const SET_TOKEN_CREATE_NETWORK = 'SET_TOKEN_CREATE_NETWORK';
export const DELETE_TOKEN_CREATE_NETWORK = 'DELETE_TOKEN_CREATE_NETWORK';

export const SET_TOKEN_FORM_DATA = 'SET_TOKEN_FORM_DATA';
export const DELETE_TOKEN_FROM_DATA = 'DELETE_TOKEN_FROM_DATA';

export const SET_TOKEN_DEPLOY_DATA = 'SET_TOKEN_DEPLOY_DATA';
export const DELETE_TOKEN_DEPLOY_DATA = 'DELETE_TOKEN_DEPLOY_DATA';

export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_LOGGED_OUT = 'SET_LOGGED_OUT';
export const SET_COLLECTION = 'SET_COLLECTION';
export const UNSET_COLLECTION = 'UNSET_COLLECTION';
export const EMPTY_COLLECTION = 'EMPTY_COLLECTION';

export const GOOGLE_SIGNUP_STARTED = 'GOOGLE_SIGNUP_STARTED';
export const GOOGLE_SIGNUP_SUCCESS = 'GOOGLE_SIGNUP_SUCCESS';
export const GOOGLE_SIGNUP_FAILURE = 'GOOGLE_SIGNUP_FAILURE';

export const NORMAL_SIGNIN_STARTED = 'NORMAL_SIGNIN_STARTED';
export const NORMAL_SIGNIN_SUCCESS = 'NORMAL_SIGNIN_SUCCESS';
export const NORMAL_SIGNIN_FAILURE = 'NORMAL_SIGNIN_FAILURE';

export const NORMAL_SIGNUP_STARTED = 'NORMAL_SIGNUP_STARTED';
export const NORMAL_SIGNUP_SUCCESS = 'NORMAL_SIGNUP_SUCCESS';
export const NORMAL_SIGNUP_FAILURE = 'NORMAL_SIGNUP_FAILURE';
